// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDuSEz62NL8Q3i975aKXiVkt319TwbZ1U',
    appId: '1:301382781151:web:5cab7d614c336253c8816a',
    messagingSenderId: '301382781151',
    projectId: 'project-health-monitor-436da',
    authDomain: 'project-health-monitor-436da.firebaseapp.com',
    storageBucket: 'project-health-monitor-436da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu9QhMIBX_ct0Yn7tNRn6P8x_PB3cNZ9Y',
    appId: '1:301382781151:android:967b8da845e98593c8816a',
    messagingSenderId: '301382781151',
    projectId: 'project-health-monitor-436da',
    storageBucket: 'project-health-monitor-436da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRWMhUNMe36Ci17qdDaMheHT5aDhF6xpE',
    appId: '1:301382781151:ios:03891ecd9b79a990c8816a',
    messagingSenderId: '301382781151',
    projectId: 'project-health-monitor-436da',
    storageBucket: 'project-health-monitor-436da.firebasestorage.app',
    iosBundleId: 'za.co.diego.keel',
  );
}
